repos:
    - repo: https://github.com/psf/black
      rev: 19.3b0
      hooks:
          - id: black
            args: [--safe]
            language_version: python3
    - repo: git://github.com/pre-commit/pre-commit-hooks
      rev: v2.4.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
