language: python
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.cache/pyenv"

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.7
      env: TOXENV=check

install:
  - pip list
  - pip install -U tox

script:
  - tox -e ${TOXENV}
