language: python
python:
    - 3.5
    - 3.6
    - 3.7
before_install:
    - python --version
    - pip install -U pip
    - pip install -U pytest
    - pip install -U pytest-xdist
install:
    - pip install .[dev]
    - pip install -U tox
script:
    - pytest -sv --boxed tests/
    - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then pre-commit run -a -v; fi
